site_name: API Guidelines
site_description: 'UKHSA API Guidelines'
site_author: 'UKSHA'
docs_dir: docs/
repo_name: 'UKHSA-Internal/api-guidelines'
repo_url: 'https://github.com/UKHSA-Internal/api-guidelines'
edit_uri: edit/main/docs/
nav:
  #- index.md
  - API Guidelines:
    - api-design-guidelines/index.md
    - api-design-guidelines/api-specifications-and-documentation.md
    - api-design-guidelines/organisational-data-models.md
    - api-design-guidelines/api-design.md
    - api-design-guidelines/naming-conventions.md
    - api-design-guidelines/security.md
    - api-design-guidelines/error-handling.md
    - api-design-guidelines/versioning-and-deprecation.md
    - api-design-guidelines/pagination-filtering-sorting.md
    - api-design-guidelines/testing.md
    - Performance, Reliability & Monitoring:
      - api-design-guidelines/caching.md
      - api-design-guidelines/resilience.md
      - api-design-guidelines/monitoring.md
    - api-design-guidelines/governance.md
    - api-design-guidelines/data-standards.md
    - api-design-guidelines/common-data-types.md
    - api-design-guidelines/integration-patterns.md
  - API Guidance Summary:
    - guidance-summary/index.md
  - Spectral Rules:
    - spectral-rules/index.md
    - MUST:
      - ... | flat | spectral-rules/must/*.md
    - SHOULD:
      - ... | flat | spectral-rules/should/*.md

theme:
  name: tech_docs_template
  custom_dir: overrides
  logo: assets/images/logo-ukhsa-landscape-new.svg
  favicon: assets/images/favicon-new.svg
  palette:
    # - primary: black
    #   accent: teal
    - scheme: default
      accent: teal

  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.expand
    #- navigation.indexes
    #- navigation.sections
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    #- toc.integrate

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css

markdown_extensions:
  - github-callouts
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - material/search
  #- search
  - awesome-pages
  - redirects:
      redirect_maps:
        'index.md': 'api-design-guidelines/index.md'
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_GIT_PROVENANCE_ENABLED, false]
      type: timeago
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [MKDOCS_GIT_PROVENANCE_ENABLED, false]
      repository: UKHSA-Internal/api-guidelines
      token: !ENV [GITHUB_TOKEN]
      branch: main
  - print-site:
      add_to_navigation: false
      add_cover_page: true
      include_css: true
      path_to_pdf: "ukhsa-api-guidelines.pdf"
      enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, false]
