site_name: UKSA API Guidelines
site_description: 'Home of UKHSA API Guidelines'
site_author: 'UKSHA'
docs_dir: docs/
repo_name: 'UKHSA-Internal/api-guidelines'
repo_url: 'https://github.com/UKHSA-Internal/api-guidelines'
edit_uri: edit/main/docs/
nav:
  - Introduction: index.md
  - api-specifications-and-documentation.md
  - api-design.md
  - naming-conventions.md
  - ...

theme:
  name: material
  logo: assets/ukhsa-logo-white.png
  palette:
    primary: black
  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view

markdown_extensions:
  - github-callouts
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - awesome-pages