nav:
  - API Guidelines:
    - api-design-guidelines/index.md
    - api-design-guidelines/api-specifications-and-documentation.md
    - api-design-guidelines/organisational-data-models.md
    - api-design-guidelines/api-design.md
    - api-design-guidelines/naming-conventions.md
    - api-design-guidelines/security.md
    - api-design-guidelines/error-handling.md
    - api-design-guidelines/versioning-and-deprecation.md
    - api-design-guidelines/pagination-filtering-sorting.md
    - api-design-guidelines/testing.md
    - Performance, Reliability & Monitoring:
      - Overview: api-design-guidelines/performance-reliability-monitoring/index.md
      - api-design-guidelines/performance-reliability-monitoring/caching.md
      - api-design-guidelines/performance-reliability-monitoring/resilience.md
      - api-design-guidelines/performance-reliability-monitoring/monitoring.md
    - api-design-guidelines/governance.md
    - api-design-guidelines/data-standards.md
    - api-design-guidelines/common-data-types.md
    - api-design-guidelines/integration-patterns.md
  - API Guidance Summary:
    - guidance-summary/index.md
  - Spectral Rules:
    - spectral-rules/index.md
    - MUST:
      - "spectral-rules/must/*.md"
    - SHOULD:
      - "spectral-rules/should/*.md"
  - Development Standards:
    - "dev-standards/index.md"
    - "dev-standards/sdlc.md"
    - "dev-standards/environments.md"
    - "dev-standards/*.md"
