name: Lint Example OpenAPI
on:
  pull_request:
    paths:
      - 'functions/*'
      - 'example/*'
      - '.spectral.yaml'
      - '*.oas.rules.*'
  push:
    paths:
      - 'functions/*'
      - 'example/*'
      - '.spectral.yaml'
      - '*.oas.rules.*'
    branches:
      - main

jobs:
  lint-example-openapi:
    name: Lint Example OpenAPI

    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install spectral
        run: curl -L https://raw.github.com/stoplightio/spectral/master/scripts/install.sh | sh

      - name: Lint example OpenAPI
        run: |
          spectral --version
          spectral lint "./example/*.{json,yml,yaml}" -f github-actions
