name: Override PR Merge Initialise

on:
  issue_comment:
    types: [created]

jobs:
  get-permissions:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      github.event.comment.body == '/merge' &&
      !github.event.issue.closed_at &&
      github.event.issue.state == 'open'

    name: Get User Permissions
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    env:
      USERNAME: ${{ github.event_name == 'issue_comment' && github.event.comment.user.login || github.actor }}

    steps:

      - name: Get permissions
        id: permission
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching permissions for user: $USERNAME"
          RESPONSE=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/$GITHUB_REPOSITORY/collaborators/$USERNAME/permission | jq -r .permission)
          echo "Permission: $RESPONSE"
          echo "permission=$RESPONSE" >> $GITHUB_OUTPUT

      # Post a failure message when any of the previous steps fail.
      - name: Add failure comment to PR
        if: ${{ !contains(fromJSON('["write", "admin"]'), steps.permission.outputs.permission) }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.issue.number }}
          body: |
            You do not have permission to merge this PR.
            Please contact a repository admin for assistance.
        run: |
          echo "Adding failure comment to PR"
          RESPONSE=$(gh pr comment $pull_number --repo "$GITHUB_REPOSITORY" -b "$body")
          echo "response: $RESPONSE"

      - name: Set failure message
        uses: actions/github-script@v7
        if: ${{ !contains(fromJSON('["write", "admin"]'), steps.permission.outputs.permission) }}
        with:
          script: core.setFailed("You do not have permission to merge this PR. Please contact a repository admin for assistance.");

      - name: Create event artifact 
        id: write_event
        env:
          event_details: ${{ toJson(github.event) }}
        run: |
          echo "$event_details" > event.json

      - name: Upload Event Artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-artifact
          path: event.json
