name: Override PR Merge Complete
on:
  workflow_run:
    workflows: ["Override PR Merge Initialise"]
    types:
      - completed

jobs:
  get-permissions:
    if: |
      github.event.workflow_run.event == 'issue_comment' &&
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest
    permissions: {}

    steps:

        - run: echo $event_details
          env:
            event_details: ${{ toJson(github.event.workflow_run) }}
