name: Override PR Merge Complete
on:
  workflow_run:
    workflows: ["Override PR Merge Initialise"]
    types:
      - completed

jobs:
  get-permissions:
    if: |
      github.event.workflow_run.event == 'issue_comment' &&
      github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest
    permissions: {}

    steps:

        - name: 'Download artifact'
          uses: actions/download-artifact@v4
          with:
            name: event-artifact
            github-token: ${{ secrets.GITHUB_TOKEN }}
            run-id: ${{ github.event.workflow_run.id }}

        - name: 'Read artifact'
          id: read-artifact
          run: |
            echo "Reading artifact"
            cat event.json

        - run: echo $event_details
          env:
            event_details: ${{ toJson(github.event.workflow_run) }}
