name: Publish to Confluence
on:
  push:
    branches:
      - main

jobs:
  publish-to-confluence:
    name: Publish Guidelines To Confluence
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish@v1
        with:
          configFile: .markdown-confluence.json
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
