name: Run TypeScript Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript tests with coverage
        run: npm test
