name: Publish Guidelines
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  run-test:
    name: Build Documentation
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged)

    # Grant GITHUB_TOKEN the permissions required to make get git provenance when building docs
    permissions:
      contents: read    # to read git committers

    runs-on: ubuntu-latest
    steps:
    - run: echo "success"
